"""Template rendering for offline ROS-style package generation."""

from __future__ import annotations

from textwrap import dedent


def package_xml(package_name: str) -> str:
    """Render a ROS-style package.xml file."""
    return dedent(
        f"""\
        <?xml version="1.0"?>
        <package format="3">
          <name>{package_name}</name>
          <version>0.1.0</version>
          <description>ROS-style package generated by RoboPilot.</description>
          <maintainer email="developer@example.com">RoboPilot User</maintainer>
          <license>MIT</license>

          <buildtool_depend>ament_python</buildtool_depend>

          <exec_depend>rclpy</exec_depend>
          <exec_depend>sensor_msgs</exec_depend>
          <exec_depend>std_msgs</exec_depend>

          <export>
            <build_type>ament_python</build_type>
          </export>
        </package>
        """
    )


def setup_py(package_name: str) -> str:
    """Render a ROS-style setup.py file."""
    return dedent(
        f"""\
        from setuptools import find_packages, setup


        package_name = "{package_name}"

        setup(
            name=package_name,
            version="0.1.0",
            packages=find_packages(exclude=["test"]),
            data_files=[
                (f"share/{{package_name}}", ["package.xml"]),
                (f"share/{{package_name}}/launch", ["launch/{package_name}.launch.py"]),
                (f"share/{{package_name}}/config", ["config/params.yaml"]),
            ],
            install_requires=["setuptools"],
            zip_safe=True,
            maintainer="RoboPilot User",
            maintainer_email="developer@example.com",
            description="ROS-style Python package generated by RoboPilot.",
            license="MIT",
            entry_points={{
                "console_scripts": [
                    "detector_node = {package_name}.detector_node:main",
                ],
            }},
        )
        """
    )


def setup_cfg(package_name: str) -> str:
    """Render a ROS-style setup.cfg file."""
    return dedent(
        f"""\
        [develop]
        script_dir=$base/lib/{package_name}

        [install]
        install_scripts=$base/lib/{package_name}
        """
    )


def readme(package_name: str, task: str) -> str:
    """Render a README for the generated package."""
    return dedent(
        f"""\
        # {package_name}

        ROS-style Python package generated by RoboPilot.

        ## Task

        {task}

        ## Generated Files

        - `package.xml`
        - `setup.py`
        - `setup.cfg`
        - `launch/{package_name}.launch.py`
        - `config/params.yaml`
        - `{package_name}/detector_node.py`

        ## Notes

        This package is intentionally offline-friendly pseudocode. It mirrors common
        ROS2 Python package structure, but the MVP does not require a real ROS2
        installation to generate or inspect these files.
        """
    )


def launch_file(package_name: str) -> str:
    """Render a ROS-style launch file."""
    return dedent(
        f"""\
        \"\"\"ROS2-style launch pseudocode for {package_name}.\"\"\"

        # This file mirrors a common ROS2 launch structure.
        # It is generated for learning and planning; RoboPilot MVP does not
        # require launch_ros or a ROS2 runtime to be installed.


        def generate_launch_description():
            try:
                from launch import LaunchDescription
                from launch_ros.actions import Node
            except ImportError:
                return {{
                    "package": "{package_name}",
                    "node": "detector_node",
                    "note": "ROS2 launch modules are not installed; this is pseudocode.",
                }}

            return LaunchDescription(
                [
                    Node(
                        package="{package_name}",
                        executable="detector_node",
                        name="detector_node",
                        output="screen",
                        parameters=["config/params.yaml"],
                    )
                ]
            )
        """
    )


def params_yaml(package_name: str) -> str:
    """Render a basic params.yaml file."""
    return dedent(
        f"""\
        {package_name}:
          detector_node:
            ros__parameters:
              input_image_topic: /camera/image_raw
              output_boxes_topic: /detections/bounding_boxes
              confidence_threshold: 0.50
              publish_debug_image: false
        """
    )


def detector_node(package_name: str, task: str) -> str:
    """Render a ROS2-style detector node pseudocode file."""
    return dedent(
        f'''\
        """ROS2-style detector node pseudocode generated by RoboPilot.

        Task:
            {task}

        This module is intentionally safe to inspect without ROS2 installed. The
        structure follows common rclpy patterns, but the fallback classes let the
        file remain importable in a plain Python environment.
        """

        from __future__ import annotations

        from dataclasses import dataclass
        from typing import Any


        try:
            import rclpy
            from rclpy.node import Node
        except ImportError:
            rclpy = None

            class Node:  # type: ignore[no-redef]
                """Tiny fallback so this pseudocode stays readable offline."""

                def __init__(self, name: str) -> None:
                    self.name = name

                def get_logger(self) -> Any:
                    return self

                def info(self, message: str) -> None:
                    print(message)


        @dataclass
        class BoundingBox:
            """Simple placeholder for a detected object bounding box."""

            label: str
            confidence: float
            x: int
            y: int
            width: int
            height: int


        class DetectorNode(Node):
            """ROS2-style object detection node skeleton."""

            def __init__(self) -> None:
                super().__init__("detector_node")
                self.input_image_topic = "/camera/image_raw"
                self.output_boxes_topic = "/detections/bounding_boxes"
                self.confidence_threshold = 0.50

                self.get_logger().info(
                    "Detector node initialized for package '{package_name}'."
                )

                # In a real ROS2 implementation, create_subscription would listen
                # to sensor_msgs/Image and create_publisher would publish detection
                # messages. RoboPilot keeps this as pseudocode for the offline MVP.
                self.image_subscription = None
                self.box_publisher = None

            def on_image(self, image_message: Any) -> list[BoundingBox]:
                """Process one image message and return placeholder detections."""
                self.get_logger().info(
                    f"Received image on {{self.input_image_topic}}: {{image_message!r}}"
                )
                return self.detect_objects(image_message)

            def detect_objects(self, image_message: Any) -> list[BoundingBox]:
                """Replace this placeholder with a model or classical CV pipeline."""
                _ = image_message
                return [
                    BoundingBox(
                        label="object",
                        confidence=0.90,
                        x=120,
                        y=80,
                        width=160,
                        height=120,
                    )
                ]

            def publish_boxes(self, boxes: list[BoundingBox]) -> None:
                """Publish bounding boxes in a real ROS2 node; log them offline."""
                self.get_logger().info(
                    f"Publishing {{len(boxes)}} boxes to {{self.output_boxes_topic}}"
                )


        def main() -> None:
            """Entry point for the ROS2-style detector node."""
            if rclpy is None:
                node = DetectorNode()
                boxes = node.on_image("<offline image placeholder>")
                node.publish_boxes(boxes)
                return

            rclpy.init()
            node = DetectorNode()
            try:
                rclpy.spin(node)
            finally:
                node.destroy_node()
                rclpy.shutdown()


        if __name__ == "__main__":
            main()
        '''
    )
