"""ROS2 launch placeholder for RoboPilot migration scaffold demos.

Generated by RoboPilot style guidance.
This is not an automatic migration. TODO: manual review required.
"""

from launch import LaunchDescription


def generate_launch_description():
    # TODO: Manually migrate ROS1 launch/demo.launch to ROS2 launch actions.
    # Review parameters, remaps, namespaces, and ROS2 QoS assumptions.
    return LaunchDescription([])
