"""ROS2-style detector node pseudocode generated by RoboPilot.

Task:
    Create an object detection node subscribing to camera images and publishing bounding boxes.

This module is intentionally safe to inspect without ROS2 installed. The
structure follows common rclpy patterns, but the fallback classes let the
file remain importable in a plain Python environment.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


try:
    import rclpy
    from rclpy.node import Node
except ImportError:
    rclpy = None

    class Node:  # type: ignore[no-redef]
        """Tiny fallback so this pseudocode stays readable offline."""

        def __init__(self, name: str) -> None:
            self.name = name

        def get_logger(self) -> Any:
            return self

        def info(self, message: str) -> None:
            print(message)


@dataclass
class BoundingBox:
    """Simple placeholder for a detected object bounding box."""

    label: str
    confidence: float
    x: int
    y: int
    width: int
    height: int


class DetectorNode(Node):
    """ROS2-style object detection node skeleton."""

    def __init__(self) -> None:
        super().__init__("detector_node")
        self.input_image_topic = "/camera/image_raw"
        self.output_boxes_topic = "/detections/bounding_boxes"
        self.confidence_threshold = 0.50

        self.get_logger().info(
            "Detector node initialized for package 'demo_detector'."
        )

        # In a real ROS2 implementation, create_subscription would listen
        # to sensor_msgs/Image and create_publisher would publish detection
        # messages. RoboPilot keeps this as pseudocode for the offline MVP.
        self.image_subscription = None
        self.box_publisher = None

    def on_image(self, image_message: Any) -> list[BoundingBox]:
        """Process one image message and return placeholder detections."""
        self.get_logger().info(
            f"Received image on {self.input_image_topic}: {image_message!r}"
        )
        return self.detect_objects(image_message)

    def detect_objects(self, image_message: Any) -> list[BoundingBox]:
        """Replace this placeholder with a model or classical CV pipeline."""
        _ = image_message
        return [
            BoundingBox(
                label="object",
                confidence=0.90,
                x=120,
                y=80,
                width=160,
                height=120,
            )
        ]

    def publish_boxes(self, boxes: list[BoundingBox]) -> None:
        """Publish bounding boxes in a real ROS2 node; log them offline."""
        self.get_logger().info(
            f"Publishing {len(boxes)} boxes to {self.output_boxes_topic}"
        )


def main() -> None:
    """Entry point for the ROS2-style detector node."""
    if rclpy is None:
        node = DetectorNode()
        boxes = node.on_image("<offline image placeholder>")
        node.publish_boxes(boxes)
        return

    rclpy.init()
    node = DetectorNode()
    try:
        rclpy.spin(node)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
